# Generated by Django 4.2.9 on 2024-01-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogpost_uploaded_video_blogpost_youtube_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(null=True, upload_to="blog_images/"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.subcategory",
            ),
        ),
    ]
