# Generated by Django 4.2.9 on 2024-01-23 10:19

import blog.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_image_alter_blogpost_uploaded_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[blog.models.validate_square_image], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='uploaded_video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Please upload a square video (e.g., 480x480, 640x640).', max_length=255, null=True, verbose_name='video'),
        ),
    ]
