# Generated by Django 4.2.9 on 2024-01-30 17:02

from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogpost_image_alter_blogpost_uploaded_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="youtube_video_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the YouTube video (optional)",
                null=True,
                validators=[blog.models.validate_youtube_url],
            ),
        ),
    ]
